export enum CHAT_EVENT_ACTION {
  chatEventMessageEdited = 'chatEventMessageEdited',
  chatEventMessageDeleted = 'chatEventMessageDeleted',
  chatEventPollStopped = 'chatEventPollStopped',
  chatEventMessagePinned = 'chatEventMessagePinned',
  chatEventMessageUnpinned = 'chatEventMessageUnpinned',
  chatEventMemberJoined = 'chatEventMemberJoined',
  chatEventMemberLeft = 'chatEventMemberLeft',
  chatEventMemberInvited = 'chatEventMemberInvited',
  chatEventMemberPromoted = 'chatEventMemberPromoted',
  chatEventMemberRestricted = 'chatEventMemberRestricted',
  chatEventTitleChanged = 'chatEventTitleChanged',
  chatEventPermissionsChanged = 'chatEventPermissionsChanged',
  chatEventDescriptionChanged = 'chatEventDescriptionChanged',
  chatEventUsernameChanged = 'chatEventUsernameChanged',
  chatEventPhotoChanged = 'chatEventPhotoChanged',
  chatEventInvitesToggled = 'chatEventInvitesToggled',
  chatEventSignMessagesToggled = 'chatEventSignMessagesToggled',
  chatEventStickerSetChanged = 'chatEventStickerSetChanged',
  chatEventIsAllHistoryAvailableToggled = 'chatEventIsAllHistoryAvailableToggled'
}
