export enum INTERNAL_LINK_TYPE {
  internalLinkTypeActiveSessions = 'internalLinkTypeActiveSessions',
  internalLinkTypeAuthenticationCode = 'internalLinkTypeAuthenticationCode',
  internalLinkTypeBackground = 'internalLinkTypeBackground',
  internalLinkTypeBotStart = 'internalLinkTypeBotStart',
  internalLinkTypeBotStartInGroup = 'internalLinkTypeBotStartInGroup',
  internalLinkTypeChangePhoneNumber = 'internalLinkTypeChangePhoneNumber',
  internalLinkTypeChatInvite = 'internalLinkTypeChatInvite',
  internalLinkTypeFilterSettings = 'internalLinkTypeFilterSettings',
  internalLinkTypeGame = 'internalLinkTypeGame',
  internalLinkTypeLanguagePack = 'internalLinkTypeLanguagePack',
  internalLinkTypeMessage = 'internalLinkTypeMessage',
  internalLinkTypeMessageDraft = 'internalLinkTypeMessageDraft',
  internalLinkTypePassportDataRequest = 'internalLinkTypePassportDataRequest',
  internalLinkTypePhoneNumberConfirmation = 'internalLinkTypePhoneNumberConfirmation',
  internalLinkTypeProxy = 'internalLinkTypeProxy',
  internalLinkTypePublicChat = 'internalLinkTypePublicChat',
  internalLinkTypeQrCodeAuthentication = 'internalLinkTypeQrCodeAuthentication',
  internalLinkTypeSettings = 'internalLinkTypeSettings',
  internalLinkTypeStickerSet = 'internalLinkTypeStickerSet',
  internalLinkTypeTheme = 'internalLinkTypeTheme',
  internalLinkTypeThemeSettings = 'internalLinkTypeThemeSettings',
  internalLinkTypeUnknownDeepLink = 'internalLinkTypeUnknownDeepLink',
  internalLinkTypeUnsupportedProxy = 'internalLinkTypeUnsupportedProxy',
  internalLinkTypeVideoChat = 'internalLinkTypeVideoChat'
}
