import * as api from './methods'

export interface ApiMethods {
  acceptCall: api.acceptCall
  acceptTermsOfService: api.acceptTermsOfService
  addChatMember: api.addChatMember
  addChatMembers: api.addChatMembers
  addCustomServerLanguagePack: api.addCustomServerLanguagePack
  addFavoriteSticker: api.addFavoriteSticker
  addLocalMessage: api.addLocalMessage
  addLogMessage: api.addLogMessage
  addNetworkStatistics: api.addNetworkStatistics
  addProxy: api.addProxy
  addRecentSticker: api.addRecentSticker
  addRecentlyFoundChat: api.addRecentlyFoundChat
  addSavedAnimation: api.addSavedAnimation
  addStickerToSet: api.addStickerToSet
  answerCallbackQuery: api.answerCallbackQuery
  answerCustomQuery: api.answerCustomQuery
  answerInlineQuery: api.answerInlineQuery
  answerPreCheckoutQuery: api.answerPreCheckoutQuery
  answerShippingQuery: api.answerShippingQuery
  blockUser: api.blockUser
  cancelDownloadFile: api.cancelDownloadFile
  cancelUploadFile: api.cancelUploadFile
  changeChatReportSpamState: api.changeChatReportSpamState
  changeImportedContacts: api.changeImportedContacts
  changePhoneNumber: api.changePhoneNumber
  changeStickerSet: api.changeStickerSet
  checkAuthenticationBotToken: api.checkAuthenticationBotToken
  checkAuthenticationCode: api.checkAuthenticationCode
  checkAuthenticationPassword: api.checkAuthenticationPassword
  checkChangePhoneNumberCode: api.checkChangePhoneNumberCode
  checkChatInviteLink: api.checkChatInviteLink
  checkChatUsername: api.checkChatUsername
  checkDatabaseEncryptionKey: api.checkDatabaseEncryptionKey
  checkEmailAddressVerificationCode: api.checkEmailAddressVerificationCode
  checkPhoneNumberConfirmationCode: api.checkPhoneNumberConfirmationCode
  checkPhoneNumberVerificationCode: api.checkPhoneNumberVerificationCode
  checkRecoveryEmailAddressCode: api.checkRecoveryEmailAddressCode
  cleanFileName: api.cleanFileName
  clearAllDraftMessages: api.clearAllDraftMessages
  clearImportedContacts: api.clearImportedContacts
  clearRecentStickers: api.clearRecentStickers
  clearRecentlyFoundChats: api.clearRecentlyFoundChats
  close: api.close
  closeChat: api.closeChat
  closeSecretChat: api.closeSecretChat
  createBasicGroupChat: api.createBasicGroupChat
  createCall: api.createCall
  createNewBasicGroupChat: api.createNewBasicGroupChat
  createNewSecretChat: api.createNewSecretChat
  createNewStickerSet: api.createNewStickerSet
  createNewSupergroupChat: api.createNewSupergroupChat
  createPrivateChat: api.createPrivateChat
  createSecretChat: api.createSecretChat
  createSupergroupChat: api.createSupergroupChat
  createTemporaryPassword: api.createTemporaryPassword
  deleteAccount: api.deleteAccount
  deleteChatHistory: api.deleteChatHistory
  deleteChatMessagesFromUser: api.deleteChatMessagesFromUser
  deleteChatReplyMarkup: api.deleteChatReplyMarkup
  deleteFile: api.deleteFile
  deleteLanguagePack: api.deleteLanguagePack
  deleteMessages: api.deleteMessages
  deletePassportElement: api.deletePassportElement
  deleteProfilePhoto: api.deleteProfilePhoto
  deleteSavedCredentials: api.deleteSavedCredentials
  deleteSavedOrderInfo: api.deleteSavedOrderInfo
  deleteSupergroup: api.deleteSupergroup
  destroy: api.destroy
  disableProxy: api.disableProxy
  discardCall: api.discardCall
  disconnectAllWebsites: api.disconnectAllWebsites
  disconnectWebsite: api.disconnectWebsite
  downloadFile: api.downloadFile
  editCustomLanguagePackInfo: api.editCustomLanguagePackInfo
  editInlineMessageCaption: api.editInlineMessageCaption
  editInlineMessageLiveLocation: api.editInlineMessageLiveLocation
  editInlineMessageMedia: api.editInlineMessageMedia
  editInlineMessageReplyMarkup: api.editInlineMessageReplyMarkup
  editInlineMessageText: api.editInlineMessageText
  editMessageCaption: api.editMessageCaption
  editMessageLiveLocation: api.editMessageLiveLocation
  editMessageMedia: api.editMessageMedia
  editMessageReplyMarkup: api.editMessageReplyMarkup
  editMessageText: api.editMessageText
  editProxy: api.editProxy
  enableProxy: api.enableProxy
  finishFileGeneration: api.finishFileGeneration
  forwardMessages: api.forwardMessages
  generateChatInviteLink: api.generateChatInviteLink
  getAccountTtl: api.getAccountTtl
  getActiveLiveLocationMessages: api.getActiveLiveLocationMessages
  getActiveSessions: api.getActiveSessions
  getAllPassportElements: api.getAllPassportElements
  getApplicationConfig: api.getApplicationConfig
  getArchivedStickerSets: api.getArchivedStickerSets
  getAttachedStickerSets: api.getAttachedStickerSets
  getAuthorizationState: api.getAuthorizationState
  getAutoDownloadSettingsPresets: api.getAutoDownloadSettingsPresets
  getBackgroundUrl: api.getBackgroundUrl
  getBackgrounds: api.getBackgrounds
  getBasicGroup: api.getBasicGroup
  getBasicGroupFullInfo: api.getBasicGroupFullInfo
  getBlockedUsers: api.getBlockedUsers
  getCallbackQueryAnswer: api.getCallbackQueryAnswer
  getChat: api.getChat
  getChatAdministrators: api.getChatAdministrators
  getChatEventLog: api.getChatEventLog
  getChatHistory: api.getChatHistory
  getChatMember: api.getChatMember
  getChatMessageByDate: api.getChatMessageByDate
  getChatMessageCount: api.getChatMessageCount
  getChatNotificationSettingsExceptions: api.getChatNotificationSettingsExceptions
  getChatPinnedMessage: api.getChatPinnedMessage
  getChatReportSpamState: api.getChatReportSpamState
  getChatStatisticsUrl: api.getChatStatisticsUrl
  getChats: api.getChats
  getConnectedWebsites: api.getConnectedWebsites
  getContacts: api.getContacts
  getCountryCode: api.getCountryCode
  getCreatedPublicChats: api.getCreatedPublicChats
  getCurrentState: api.getCurrentState
  getDatabaseStatistics: api.getDatabaseStatistics
  getDeepLinkInfo: api.getDeepLinkInfo
  getEmojiSuggestionsUrl: api.getEmojiSuggestionsUrl
  getFavoriteStickers: api.getFavoriteStickers
  getFile: api.getFile
  getFileDownloadedPrefixSize: api.getFileDownloadedPrefixSize
  getFileExtension: api.getFileExtension
  getFileMimeType: api.getFileMimeType
  getGameHighScores: api.getGameHighScores
  getGroupsInCommon: api.getGroupsInCommon
  getImportedContactCount: api.getImportedContactCount
  getInlineGameHighScores: api.getInlineGameHighScores
  getInlineQueryResults: api.getInlineQueryResults
  getInstalledStickerSets: api.getInstalledStickerSets
  getInviteText: api.getInviteText
  getJsonString: api.getJsonString
  getJsonValue: api.getJsonValue
  getLanguagePackInfo: api.getLanguagePackInfo
  getLanguagePackString: api.getLanguagePackString
  getLanguagePackStrings: api.getLanguagePackStrings
  getLocalizationTargetInfo: api.getLocalizationTargetInfo
  getLogStream: api.getLogStream
  getLogTagVerbosityLevel: api.getLogTagVerbosityLevel
  getLogTags: api.getLogTags
  getLogVerbosityLevel: api.getLogVerbosityLevel
  getMapThumbnailFile: api.getMapThumbnailFile
  getMe: api.getMe
  getMessage: api.getMessage
  getMessageLink: api.getMessageLink
  getMessageLinkInfo: api.getMessageLinkInfo
  getMessageLocally: api.getMessageLocally
  getMessages: api.getMessages
  getNetworkStatistics: api.getNetworkStatistics
  getOption: api.getOption
  getPassportAuthorizationForm: api.getPassportAuthorizationForm
  getPassportAuthorizationFormAvailableElements: api.getPassportAuthorizationFormAvailableElements
  getPassportElement: api.getPassportElement
  getPasswordState: api.getPasswordState
  getPaymentForm: api.getPaymentForm
  getPaymentReceipt: api.getPaymentReceipt
  getPreferredCountryLanguage: api.getPreferredCountryLanguage
  getProxies: api.getProxies
  getProxyLink: api.getProxyLink
  getPublicMessageLink: api.getPublicMessageLink
  getPushReceiverId: api.getPushReceiverId
  getRecentInlineBots: api.getRecentInlineBots
  getRecentStickers: api.getRecentStickers
  getRecentlyVisitedTMeUrls: api.getRecentlyVisitedTMeUrls
  getRecoveryEmailAddress: api.getRecoveryEmailAddress
  getRemoteFile: api.getRemoteFile
  getRepliedMessage: api.getRepliedMessage
  getSavedAnimations: api.getSavedAnimations
  getSavedOrderInfo: api.getSavedOrderInfo
  getScopeNotificationSettings: api.getScopeNotificationSettings
  getSecretChat: api.getSecretChat
  getStickerEmojis: api.getStickerEmojis
  getStickerSet: api.getStickerSet
  getStickers: api.getStickers
  getStorageStatistics: api.getStorageStatistics
  getStorageStatisticsFast: api.getStorageStatisticsFast
  getSupergroup: api.getSupergroup
  getSupergroupFullInfo: api.getSupergroupFullInfo
  getSupergroupMembers: api.getSupergroupMembers
  getSupportUser: api.getSupportUser
  getTemporaryPasswordState: api.getTemporaryPasswordState
  getTextEntities: api.getTextEntities
  getTopChats: api.getTopChats
  getTrendingStickerSets: api.getTrendingStickerSets
  getUser: api.getUser
  getUserFullInfo: api.getUserFullInfo
  getUserPrivacySettingRules: api.getUserPrivacySettingRules
  getUserProfilePhotos: api.getUserProfilePhotos
  getWebPageInstantView: api.getWebPageInstantView
  getWebPagePreview: api.getWebPagePreview
  importContacts: api.importContacts
  joinChat: api.joinChat
  joinChatByInviteLink: api.joinChatByInviteLink
  leaveChat: api.leaveChat
  logOut: api.logOut
  openChat: api.openChat
  openMessageContent: api.openMessageContent
  optimizeStorage: api.optimizeStorage
  parseTextEntities: api.parseTextEntities
  pinChatMessage: api.pinChatMessage
  pingProxy: api.pingProxy
  processPushNotification: api.processPushNotification
  readAllChatMentions: api.readAllChatMentions
  readFilePart: api.readFilePart
  recoverAuthenticationPassword: api.recoverAuthenticationPassword
  recoverPassword: api.recoverPassword
  registerDevice: api.registerDevice
  registerUser: api.registerUser
  removeBackground: api.removeBackground
  removeContacts: api.removeContacts
  removeFavoriteSticker: api.removeFavoriteSticker
  removeNotification: api.removeNotification
  removeNotificationGroup: api.removeNotificationGroup
  removeProxy: api.removeProxy
  removeRecentHashtag: api.removeRecentHashtag
  removeRecentSticker: api.removeRecentSticker
  removeRecentlyFoundChat: api.removeRecentlyFoundChat
  removeSavedAnimation: api.removeSavedAnimation
  removeStickerFromSet: api.removeStickerFromSet
  removeTopChat: api.removeTopChat
  reorderInstalledStickerSets: api.reorderInstalledStickerSets
  reportChat: api.reportChat
  reportSupergroupSpam: api.reportSupergroupSpam
  requestAuthenticationPasswordRecovery: api.requestAuthenticationPasswordRecovery
  requestPasswordRecovery: api.requestPasswordRecovery
  resendAuthenticationCode: api.resendAuthenticationCode
  resendChangePhoneNumberCode: api.resendChangePhoneNumberCode
  resendEmailAddressVerificationCode: api.resendEmailAddressVerificationCode
  resendMessages: api.resendMessages
  resendPhoneNumberConfirmationCode: api.resendPhoneNumberConfirmationCode
  resendPhoneNumberVerificationCode: api.resendPhoneNumberVerificationCode
  resendRecoveryEmailAddressCode: api.resendRecoveryEmailAddressCode
  resetAllNotificationSettings: api.resetAllNotificationSettings
  resetBackgrounds: api.resetBackgrounds
  resetNetworkStatistics: api.resetNetworkStatistics
  saveApplicationLogEvent: api.saveApplicationLogEvent
  searchBackground: api.searchBackground
  searchCallMessages: api.searchCallMessages
  searchChatMembers: api.searchChatMembers
  searchChatMessages: api.searchChatMessages
  searchChatRecentLocationMessages: api.searchChatRecentLocationMessages
  searchChats: api.searchChats
  searchChatsOnServer: api.searchChatsOnServer
  searchContacts: api.searchContacts
  searchEmojis: api.searchEmojis
  searchHashtags: api.searchHashtags
  searchInstalledStickerSets: api.searchInstalledStickerSets
  searchMessages: api.searchMessages
  searchPublicChat: api.searchPublicChat
  searchPublicChats: api.searchPublicChats
  searchSecretMessages: api.searchSecretMessages
  searchStickerSet: api.searchStickerSet
  searchStickerSets: api.searchStickerSets
  searchStickers: api.searchStickers
  sendBotStartMessage: api.sendBotStartMessage
  sendCallDebugInformation: api.sendCallDebugInformation
  sendCallRating: api.sendCallRating
  sendChatAction: api.sendChatAction
  sendChatScreenshotTakenNotification: api.sendChatScreenshotTakenNotification
  sendChatSetTtlMessage: api.sendChatSetTtlMessage
  sendCustomRequest: api.sendCustomRequest
  sendEmailAddressVerificationCode: api.sendEmailAddressVerificationCode
  sendInlineQueryResultMessage: api.sendInlineQueryResultMessage
  sendMessage: api.sendMessage
  sendMessageAlbum: api.sendMessageAlbum
  sendPassportAuthorizationForm: api.sendPassportAuthorizationForm
  sendPaymentForm: api.sendPaymentForm
  sendPhoneNumberConfirmationCode: api.sendPhoneNumberConfirmationCode
  sendPhoneNumberVerificationCode: api.sendPhoneNumberVerificationCode
  setAccountTtl: api.setAccountTtl
  setAlarm: api.setAlarm
  setAuthenticationPhoneNumber: api.setAuthenticationPhoneNumber
  setAutoDownloadSettings: api.setAutoDownloadSettings
  setBackground: api.setBackground
  setBio: api.setBio
  setBotUpdatesStatus: api.setBotUpdatesStatus
  setChatClientData: api.setChatClientData
  setChatDescription: api.setChatDescription
  setChatDraftMessage: api.setChatDraftMessage
  setChatMemberStatus: api.setChatMemberStatus
  setChatNotificationSettings: api.setChatNotificationSettings
  setChatPermissions: api.setChatPermissions
  setChatPhoto: api.setChatPhoto
  setChatTitle: api.setChatTitle
  setCustomLanguagePack: api.setCustomLanguagePack
  setCustomLanguagePackString: api.setCustomLanguagePackString
  setDatabaseEncryptionKey: api.setDatabaseEncryptionKey
  setFileGenerationProgress: api.setFileGenerationProgress
  setGameScore: api.setGameScore
  setInlineGameScore: api.setInlineGameScore
  setLogStream: api.setLogStream
  setLogTagVerbosityLevel: api.setLogTagVerbosityLevel
  setLogVerbosityLevel: api.setLogVerbosityLevel
  setName: api.setName
  setNetworkType: api.setNetworkType
  setOption: api.setOption
  setPassportElement: api.setPassportElement
  setPassportElementErrors: api.setPassportElementErrors
  setPassword: api.setPassword
  setPinnedChats: api.setPinnedChats
  setPollAnswer: api.setPollAnswer
  setProfilePhoto: api.setProfilePhoto
  setRecoveryEmailAddress: api.setRecoveryEmailAddress
  setScopeNotificationSettings: api.setScopeNotificationSettings
  setStickerPositionInSet: api.setStickerPositionInSet
  setSupergroupStickerSet: api.setSupergroupStickerSet
  setSupergroupUsername: api.setSupergroupUsername
  setTdlibParameters: api.setTdlibParameters
  setUserPrivacySettingRules: api.setUserPrivacySettingRules
  setUsername: api.setUsername
  stopPoll: api.stopPoll
  synchronizeLanguagePack: api.synchronizeLanguagePack
  terminateAllOtherSessions: api.terminateAllOtherSessions
  terminateSession: api.terminateSession
  testCallBytes: api.testCallBytes
  testCallEmpty: api.testCallEmpty
  testCallString: api.testCallString
  testCallVectorInt: api.testCallVectorInt
  testCallVectorIntObject: api.testCallVectorIntObject
  testCallVectorString: api.testCallVectorString
  testCallVectorStringObject: api.testCallVectorStringObject
  testGetDifference: api.testGetDifference
  testNetwork: api.testNetwork
  testProxy: api.testProxy
  testReturnError: api.testReturnError
  testSquareInt: api.testSquareInt
  testUseUpdate: api.testUseUpdate
  toggleChatDefaultDisableNotification: api.toggleChatDefaultDisableNotification
  toggleChatIsMarkedAsUnread: api.toggleChatIsMarkedAsUnread
  toggleChatIsPinned: api.toggleChatIsPinned
  toggleSupergroupIsAllHistoryAvailable: api.toggleSupergroupIsAllHistoryAvailable
  toggleSupergroupSignMessages: api.toggleSupergroupSignMessages
  unblockUser: api.unblockUser
  unpinChatMessage: api.unpinChatMessage
  upgradeBasicGroupChatToSupergroupChat: api.upgradeBasicGroupChatToSupergroupChat
  uploadFile: api.uploadFile
  uploadStickerFile: api.uploadStickerFile
  validateOrderInfo: api.validateOrderInfo
  viewMessages: api.viewMessages
  viewTrendingStickerSets: api.viewTrendingStickerSets
  writeGeneratedFilePart: api.writeGeneratedFilePart
}
