import * as api from './methods'

export interface ApiMethods<ExtensionT> {
  acceptCall: api.acceptCall<ExtensionT>
  acceptTermsOfService: api.acceptTermsOfService<ExtensionT>
  addChatMember: api.addChatMember<ExtensionT>
  addChatMembers: api.addChatMembers<ExtensionT>
  addCustomServerLanguagePack: api.addCustomServerLanguagePack<ExtensionT>
  addFavoriteSticker: api.addFavoriteSticker<ExtensionT>
  addLocalMessage: api.addLocalMessage<ExtensionT>
  addLogMessage: api.addLogMessage<ExtensionT>
  addNetworkStatistics: api.addNetworkStatistics<ExtensionT>
  addProxy: api.addProxy<ExtensionT>
  addRecentSticker: api.addRecentSticker<ExtensionT>
  addRecentlyFoundChat: api.addRecentlyFoundChat<ExtensionT>
  addSavedAnimation: api.addSavedAnimation<ExtensionT>
  addStickerToSet: api.addStickerToSet<ExtensionT>
  answerCallbackQuery: api.answerCallbackQuery<ExtensionT>
  answerCustomQuery: api.answerCustomQuery<ExtensionT>
  answerInlineQuery: api.answerInlineQuery<ExtensionT>
  answerPreCheckoutQuery: api.answerPreCheckoutQuery<ExtensionT>
  answerShippingQuery: api.answerShippingQuery<ExtensionT>
  blockUser: api.blockUser<ExtensionT>
  cancelDownloadFile: api.cancelDownloadFile<ExtensionT>
  cancelUploadFile: api.cancelUploadFile<ExtensionT>
  changeChatReportSpamState: api.changeChatReportSpamState<ExtensionT>
  changeImportedContacts: api.changeImportedContacts<ExtensionT>
  changePhoneNumber: api.changePhoneNumber<ExtensionT>
  changeStickerSet: api.changeStickerSet<ExtensionT>
  checkAuthenticationBotToken: api.checkAuthenticationBotToken<ExtensionT>
  checkAuthenticationCode: api.checkAuthenticationCode<ExtensionT>
  checkAuthenticationPassword: api.checkAuthenticationPassword<ExtensionT>
  checkChangePhoneNumberCode: api.checkChangePhoneNumberCode<ExtensionT>
  checkChatInviteLink: api.checkChatInviteLink<ExtensionT>
  checkChatUsername: api.checkChatUsername<ExtensionT>
  checkDatabaseEncryptionKey: api.checkDatabaseEncryptionKey<ExtensionT>
  checkEmailAddressVerificationCode: api.checkEmailAddressVerificationCode<ExtensionT>
  checkPhoneNumberConfirmationCode: api.checkPhoneNumberConfirmationCode<ExtensionT>
  checkPhoneNumberVerificationCode: api.checkPhoneNumberVerificationCode<ExtensionT>
  checkRecoveryEmailAddressCode: api.checkRecoveryEmailAddressCode<ExtensionT>
  cleanFileName: api.cleanFileName<ExtensionT>
  clearAllDraftMessages: api.clearAllDraftMessages<ExtensionT>
  clearImportedContacts: api.clearImportedContacts<ExtensionT>
  clearRecentStickers: api.clearRecentStickers<ExtensionT>
  clearRecentlyFoundChats: api.clearRecentlyFoundChats<ExtensionT>
  close: api.close<ExtensionT>
  closeChat: api.closeChat<ExtensionT>
  closeSecretChat: api.closeSecretChat<ExtensionT>
  createBasicGroupChat: api.createBasicGroupChat<ExtensionT>
  createCall: api.createCall<ExtensionT>
  createNewBasicGroupChat: api.createNewBasicGroupChat<ExtensionT>
  createNewSecretChat: api.createNewSecretChat<ExtensionT>
  createNewStickerSet: api.createNewStickerSet<ExtensionT>
  createNewSupergroupChat: api.createNewSupergroupChat<ExtensionT>
  createPrivateChat: api.createPrivateChat<ExtensionT>
  createSecretChat: api.createSecretChat<ExtensionT>
  createSupergroupChat: api.createSupergroupChat<ExtensionT>
  createTemporaryPassword: api.createTemporaryPassword<ExtensionT>
  deleteAccount: api.deleteAccount<ExtensionT>
  deleteChatHistory: api.deleteChatHistory<ExtensionT>
  deleteChatMessagesFromUser: api.deleteChatMessagesFromUser<ExtensionT>
  deleteChatReplyMarkup: api.deleteChatReplyMarkup<ExtensionT>
  deleteFile: api.deleteFile<ExtensionT>
  deleteLanguagePack: api.deleteLanguagePack<ExtensionT>
  deleteMessages: api.deleteMessages<ExtensionT>
  deletePassportElement: api.deletePassportElement<ExtensionT>
  deleteProfilePhoto: api.deleteProfilePhoto<ExtensionT>
  deleteSavedCredentials: api.deleteSavedCredentials<ExtensionT>
  deleteSavedOrderInfo: api.deleteSavedOrderInfo<ExtensionT>
  deleteSupergroup: api.deleteSupergroup<ExtensionT>
  destroy: api.destroy<ExtensionT>
  disableProxy: api.disableProxy<ExtensionT>
  discardCall: api.discardCall<ExtensionT>
  disconnectAllWebsites: api.disconnectAllWebsites<ExtensionT>
  disconnectWebsite: api.disconnectWebsite<ExtensionT>
  downloadFile: api.downloadFile<ExtensionT>
  editCustomLanguagePackInfo: api.editCustomLanguagePackInfo<ExtensionT>
  editInlineMessageCaption: api.editInlineMessageCaption<ExtensionT>
  editInlineMessageLiveLocation: api.editInlineMessageLiveLocation<ExtensionT>
  editInlineMessageMedia: api.editInlineMessageMedia<ExtensionT>
  editInlineMessageReplyMarkup: api.editInlineMessageReplyMarkup<ExtensionT>
  editInlineMessageText: api.editInlineMessageText<ExtensionT>
  editMessageCaption: api.editMessageCaption<ExtensionT>
  editMessageLiveLocation: api.editMessageLiveLocation<ExtensionT>
  editMessageMedia: api.editMessageMedia<ExtensionT>
  editMessageReplyMarkup: api.editMessageReplyMarkup<ExtensionT>
  editMessageText: api.editMessageText<ExtensionT>
  editProxy: api.editProxy<ExtensionT>
  enableProxy: api.enableProxy<ExtensionT>
  finishFileGeneration: api.finishFileGeneration<ExtensionT>
  forwardMessages: api.forwardMessages<ExtensionT>
  generateChatInviteLink: api.generateChatInviteLink<ExtensionT>
  getAccountTtl: api.getAccountTtl<ExtensionT>
  getActiveLiveLocationMessages: api.getActiveLiveLocationMessages<ExtensionT>
  getActiveSessions: api.getActiveSessions<ExtensionT>
  getAllPassportElements: api.getAllPassportElements<ExtensionT>
  getApplicationConfig: api.getApplicationConfig<ExtensionT>
  getArchivedStickerSets: api.getArchivedStickerSets<ExtensionT>
  getAttachedStickerSets: api.getAttachedStickerSets<ExtensionT>
  getAuthorizationState: api.getAuthorizationState<ExtensionT>
  getAutoDownloadSettingsPresets: api.getAutoDownloadSettingsPresets<ExtensionT>
  getBackgroundUrl: api.getBackgroundUrl<ExtensionT>
  getBackgrounds: api.getBackgrounds<ExtensionT>
  getBasicGroup: api.getBasicGroup<ExtensionT>
  getBasicGroupFullInfo: api.getBasicGroupFullInfo<ExtensionT>
  getBlockedUsers: api.getBlockedUsers<ExtensionT>
  getCallbackQueryAnswer: api.getCallbackQueryAnswer<ExtensionT>
  getChat: api.getChat<ExtensionT>
  getChatAdministrators: api.getChatAdministrators<ExtensionT>
  getChatEventLog: api.getChatEventLog<ExtensionT>
  getChatHistory: api.getChatHistory<ExtensionT>
  getChatMember: api.getChatMember<ExtensionT>
  getChatMessageByDate: api.getChatMessageByDate<ExtensionT>
  getChatMessageCount: api.getChatMessageCount<ExtensionT>
  getChatNotificationSettingsExceptions: api.getChatNotificationSettingsExceptions<ExtensionT>
  getChatPinnedMessage: api.getChatPinnedMessage<ExtensionT>
  getChatReportSpamState: api.getChatReportSpamState<ExtensionT>
  getChatStatisticsUrl: api.getChatStatisticsUrl<ExtensionT>
  getChats: api.getChats<ExtensionT>
  getConnectedWebsites: api.getConnectedWebsites<ExtensionT>
  getContacts: api.getContacts<ExtensionT>
  getCountryCode: api.getCountryCode<ExtensionT>
  getCreatedPublicChats: api.getCreatedPublicChats<ExtensionT>
  getCurrentState: api.getCurrentState<ExtensionT>
  getDatabaseStatistics: api.getDatabaseStatistics<ExtensionT>
  getDeepLinkInfo: api.getDeepLinkInfo<ExtensionT>
  getEmojiSuggestionsUrl: api.getEmojiSuggestionsUrl<ExtensionT>
  getFavoriteStickers: api.getFavoriteStickers<ExtensionT>
  getFile: api.getFile<ExtensionT>
  getFileDownloadedPrefixSize: api.getFileDownloadedPrefixSize<ExtensionT>
  getFileExtension: api.getFileExtension<ExtensionT>
  getFileMimeType: api.getFileMimeType<ExtensionT>
  getGameHighScores: api.getGameHighScores<ExtensionT>
  getGroupsInCommon: api.getGroupsInCommon<ExtensionT>
  getImportedContactCount: api.getImportedContactCount<ExtensionT>
  getInlineGameHighScores: api.getInlineGameHighScores<ExtensionT>
  getInlineQueryResults: api.getInlineQueryResults<ExtensionT>
  getInstalledStickerSets: api.getInstalledStickerSets<ExtensionT>
  getInviteText: api.getInviteText<ExtensionT>
  getJsonString: api.getJsonString<ExtensionT>
  getJsonValue: api.getJsonValue<ExtensionT>
  getLanguagePackInfo: api.getLanguagePackInfo<ExtensionT>
  getLanguagePackString: api.getLanguagePackString<ExtensionT>
  getLanguagePackStrings: api.getLanguagePackStrings<ExtensionT>
  getLocalizationTargetInfo: api.getLocalizationTargetInfo<ExtensionT>
  getLogStream: api.getLogStream<ExtensionT>
  getLogTagVerbosityLevel: api.getLogTagVerbosityLevel<ExtensionT>
  getLogTags: api.getLogTags<ExtensionT>
  getLogVerbosityLevel: api.getLogVerbosityLevel<ExtensionT>
  getMapThumbnailFile: api.getMapThumbnailFile<ExtensionT>
  getMe: api.getMe<ExtensionT>
  getMessage: api.getMessage<ExtensionT>
  getMessageLink: api.getMessageLink<ExtensionT>
  getMessageLinkInfo: api.getMessageLinkInfo<ExtensionT>
  getMessageLocally: api.getMessageLocally<ExtensionT>
  getMessages: api.getMessages<ExtensionT>
  getNetworkStatistics: api.getNetworkStatistics<ExtensionT>
  getOption: api.getOption<ExtensionT>
  getPassportAuthorizationForm: api.getPassportAuthorizationForm<ExtensionT>
  getPassportAuthorizationFormAvailableElements: api.getPassportAuthorizationFormAvailableElements<ExtensionT>
  getPassportElement: api.getPassportElement<ExtensionT>
  getPasswordState: api.getPasswordState<ExtensionT>
  getPaymentForm: api.getPaymentForm<ExtensionT>
  getPaymentReceipt: api.getPaymentReceipt<ExtensionT>
  getPreferredCountryLanguage: api.getPreferredCountryLanguage<ExtensionT>
  getProxies: api.getProxies<ExtensionT>
  getProxyLink: api.getProxyLink<ExtensionT>
  getPublicMessageLink: api.getPublicMessageLink<ExtensionT>
  getPushReceiverId: api.getPushReceiverId<ExtensionT>
  getRecentInlineBots: api.getRecentInlineBots<ExtensionT>
  getRecentStickers: api.getRecentStickers<ExtensionT>
  getRecentlyVisitedTMeUrls: api.getRecentlyVisitedTMeUrls<ExtensionT>
  getRecoveryEmailAddress: api.getRecoveryEmailAddress<ExtensionT>
  getRemoteFile: api.getRemoteFile<ExtensionT>
  getRepliedMessage: api.getRepliedMessage<ExtensionT>
  getSavedAnimations: api.getSavedAnimations<ExtensionT>
  getSavedOrderInfo: api.getSavedOrderInfo<ExtensionT>
  getScopeNotificationSettings: api.getScopeNotificationSettings<ExtensionT>
  getSecretChat: api.getSecretChat<ExtensionT>
  getStickerEmojis: api.getStickerEmojis<ExtensionT>
  getStickerSet: api.getStickerSet<ExtensionT>
  getStickers: api.getStickers<ExtensionT>
  getStorageStatistics: api.getStorageStatistics<ExtensionT>
  getStorageStatisticsFast: api.getStorageStatisticsFast<ExtensionT>
  getSupergroup: api.getSupergroup<ExtensionT>
  getSupergroupFullInfo: api.getSupergroupFullInfo<ExtensionT>
  getSupergroupMembers: api.getSupergroupMembers<ExtensionT>
  getSupportUser: api.getSupportUser<ExtensionT>
  getTemporaryPasswordState: api.getTemporaryPasswordState<ExtensionT>
  getTextEntities: api.getTextEntities<ExtensionT>
  getTopChats: api.getTopChats<ExtensionT>
  getTrendingStickerSets: api.getTrendingStickerSets<ExtensionT>
  getUser: api.getUser<ExtensionT>
  getUserFullInfo: api.getUserFullInfo<ExtensionT>
  getUserPrivacySettingRules: api.getUserPrivacySettingRules<ExtensionT>
  getUserProfilePhotos: api.getUserProfilePhotos<ExtensionT>
  getWebPageInstantView: api.getWebPageInstantView<ExtensionT>
  getWebPagePreview: api.getWebPagePreview<ExtensionT>
  importContacts: api.importContacts<ExtensionT>
  joinChat: api.joinChat<ExtensionT>
  joinChatByInviteLink: api.joinChatByInviteLink<ExtensionT>
  leaveChat: api.leaveChat<ExtensionT>
  logOut: api.logOut<ExtensionT>
  openChat: api.openChat<ExtensionT>
  openMessageContent: api.openMessageContent<ExtensionT>
  optimizeStorage: api.optimizeStorage<ExtensionT>
  parseTextEntities: api.parseTextEntities<ExtensionT>
  pinChatMessage: api.pinChatMessage<ExtensionT>
  pingProxy: api.pingProxy<ExtensionT>
  processPushNotification: api.processPushNotification<ExtensionT>
  readAllChatMentions: api.readAllChatMentions<ExtensionT>
  readFilePart: api.readFilePart<ExtensionT>
  recoverAuthenticationPassword: api.recoverAuthenticationPassword<ExtensionT>
  recoverPassword: api.recoverPassword<ExtensionT>
  registerDevice: api.registerDevice<ExtensionT>
  registerUser: api.registerUser<ExtensionT>
  removeBackground: api.removeBackground<ExtensionT>
  removeContacts: api.removeContacts<ExtensionT>
  removeFavoriteSticker: api.removeFavoriteSticker<ExtensionT>
  removeNotification: api.removeNotification<ExtensionT>
  removeNotificationGroup: api.removeNotificationGroup<ExtensionT>
  removeProxy: api.removeProxy<ExtensionT>
  removeRecentHashtag: api.removeRecentHashtag<ExtensionT>
  removeRecentSticker: api.removeRecentSticker<ExtensionT>
  removeRecentlyFoundChat: api.removeRecentlyFoundChat<ExtensionT>
  removeSavedAnimation: api.removeSavedAnimation<ExtensionT>
  removeStickerFromSet: api.removeStickerFromSet<ExtensionT>
  removeTopChat: api.removeTopChat<ExtensionT>
  reorderInstalledStickerSets: api.reorderInstalledStickerSets<ExtensionT>
  reportChat: api.reportChat<ExtensionT>
  reportSupergroupSpam: api.reportSupergroupSpam<ExtensionT>
  requestAuthenticationPasswordRecovery: api.requestAuthenticationPasswordRecovery<ExtensionT>
  requestPasswordRecovery: api.requestPasswordRecovery<ExtensionT>
  resendAuthenticationCode: api.resendAuthenticationCode<ExtensionT>
  resendChangePhoneNumberCode: api.resendChangePhoneNumberCode<ExtensionT>
  resendEmailAddressVerificationCode: api.resendEmailAddressVerificationCode<ExtensionT>
  resendMessages: api.resendMessages<ExtensionT>
  resendPhoneNumberConfirmationCode: api.resendPhoneNumberConfirmationCode<ExtensionT>
  resendPhoneNumberVerificationCode: api.resendPhoneNumberVerificationCode<ExtensionT>
  resendRecoveryEmailAddressCode: api.resendRecoveryEmailAddressCode<ExtensionT>
  resetAllNotificationSettings: api.resetAllNotificationSettings<ExtensionT>
  resetBackgrounds: api.resetBackgrounds<ExtensionT>
  resetNetworkStatistics: api.resetNetworkStatistics<ExtensionT>
  saveApplicationLogEvent: api.saveApplicationLogEvent<ExtensionT>
  searchBackground: api.searchBackground<ExtensionT>
  searchCallMessages: api.searchCallMessages<ExtensionT>
  searchChatMembers: api.searchChatMembers<ExtensionT>
  searchChatMessages: api.searchChatMessages<ExtensionT>
  searchChatRecentLocationMessages: api.searchChatRecentLocationMessages<ExtensionT>
  searchChats: api.searchChats<ExtensionT>
  searchChatsOnServer: api.searchChatsOnServer<ExtensionT>
  searchContacts: api.searchContacts<ExtensionT>
  searchEmojis: api.searchEmojis<ExtensionT>
  searchHashtags: api.searchHashtags<ExtensionT>
  searchInstalledStickerSets: api.searchInstalledStickerSets<ExtensionT>
  searchMessages: api.searchMessages<ExtensionT>
  searchPublicChat: api.searchPublicChat<ExtensionT>
  searchPublicChats: api.searchPublicChats<ExtensionT>
  searchSecretMessages: api.searchSecretMessages<ExtensionT>
  searchStickerSet: api.searchStickerSet<ExtensionT>
  searchStickerSets: api.searchStickerSets<ExtensionT>
  searchStickers: api.searchStickers<ExtensionT>
  sendBotStartMessage: api.sendBotStartMessage<ExtensionT>
  sendCallDebugInformation: api.sendCallDebugInformation<ExtensionT>
  sendCallRating: api.sendCallRating<ExtensionT>
  sendChatAction: api.sendChatAction<ExtensionT>
  sendChatScreenshotTakenNotification: api.sendChatScreenshotTakenNotification<ExtensionT>
  sendChatSetTtlMessage: api.sendChatSetTtlMessage<ExtensionT>
  sendCustomRequest: api.sendCustomRequest<ExtensionT>
  sendEmailAddressVerificationCode: api.sendEmailAddressVerificationCode<ExtensionT>
  sendInlineQueryResultMessage: api.sendInlineQueryResultMessage<ExtensionT>
  sendMessage: api.sendMessage<ExtensionT>
  sendMessageAlbum: api.sendMessageAlbum<ExtensionT>
  sendPassportAuthorizationForm: api.sendPassportAuthorizationForm<ExtensionT>
  sendPaymentForm: api.sendPaymentForm<ExtensionT>
  sendPhoneNumberConfirmationCode: api.sendPhoneNumberConfirmationCode<ExtensionT>
  sendPhoneNumberVerificationCode: api.sendPhoneNumberVerificationCode<ExtensionT>
  setAccountTtl: api.setAccountTtl<ExtensionT>
  setAlarm: api.setAlarm<ExtensionT>
  setAuthenticationPhoneNumber: api.setAuthenticationPhoneNumber<ExtensionT>
  setAutoDownloadSettings: api.setAutoDownloadSettings<ExtensionT>
  setBackground: api.setBackground<ExtensionT>
  setBio: api.setBio<ExtensionT>
  setBotUpdatesStatus: api.setBotUpdatesStatus<ExtensionT>
  setChatClientData: api.setChatClientData<ExtensionT>
  setChatDescription: api.setChatDescription<ExtensionT>
  setChatDraftMessage: api.setChatDraftMessage<ExtensionT>
  setChatMemberStatus: api.setChatMemberStatus<ExtensionT>
  setChatNotificationSettings: api.setChatNotificationSettings<ExtensionT>
  setChatPermissions: api.setChatPermissions<ExtensionT>
  setChatPhoto: api.setChatPhoto<ExtensionT>
  setChatTitle: api.setChatTitle<ExtensionT>
  setCustomLanguagePack: api.setCustomLanguagePack<ExtensionT>
  setCustomLanguagePackString: api.setCustomLanguagePackString<ExtensionT>
  setDatabaseEncryptionKey: api.setDatabaseEncryptionKey<ExtensionT>
  setFileGenerationProgress: api.setFileGenerationProgress<ExtensionT>
  setGameScore: api.setGameScore<ExtensionT>
  setInlineGameScore: api.setInlineGameScore<ExtensionT>
  setLogStream: api.setLogStream<ExtensionT>
  setLogTagVerbosityLevel: api.setLogTagVerbosityLevel<ExtensionT>
  setLogVerbosityLevel: api.setLogVerbosityLevel<ExtensionT>
  setName: api.setName<ExtensionT>
  setNetworkType: api.setNetworkType<ExtensionT>
  setOption: api.setOption<ExtensionT>
  setPassportElement: api.setPassportElement<ExtensionT>
  setPassportElementErrors: api.setPassportElementErrors<ExtensionT>
  setPassword: api.setPassword<ExtensionT>
  setPinnedChats: api.setPinnedChats<ExtensionT>
  setPollAnswer: api.setPollAnswer<ExtensionT>
  setProfilePhoto: api.setProfilePhoto<ExtensionT>
  setRecoveryEmailAddress: api.setRecoveryEmailAddress<ExtensionT>
  setScopeNotificationSettings: api.setScopeNotificationSettings<ExtensionT>
  setStickerPositionInSet: api.setStickerPositionInSet<ExtensionT>
  setSupergroupStickerSet: api.setSupergroupStickerSet<ExtensionT>
  setSupergroupUsername: api.setSupergroupUsername<ExtensionT>
  setTdlibParameters: api.setTdlibParameters<ExtensionT>
  setUserPrivacySettingRules: api.setUserPrivacySettingRules<ExtensionT>
  setUsername: api.setUsername<ExtensionT>
  stopPoll: api.stopPoll<ExtensionT>
  synchronizeLanguagePack: api.synchronizeLanguagePack<ExtensionT>
  terminateAllOtherSessions: api.terminateAllOtherSessions<ExtensionT>
  terminateSession: api.terminateSession<ExtensionT>
  testCallBytes: api.testCallBytes<ExtensionT>
  testCallEmpty: api.testCallEmpty<ExtensionT>
  testCallString: api.testCallString<ExtensionT>
  testCallVectorInt: api.testCallVectorInt<ExtensionT>
  testCallVectorIntObject: api.testCallVectorIntObject<ExtensionT>
  testCallVectorString: api.testCallVectorString<ExtensionT>
  testCallVectorStringObject: api.testCallVectorStringObject<ExtensionT>
  testGetDifference: api.testGetDifference<ExtensionT>
  testNetwork: api.testNetwork<ExtensionT>
  testProxy: api.testProxy<ExtensionT>
  testReturnError: api.testReturnError<ExtensionT>
  testSquareInt: api.testSquareInt<ExtensionT>
  testUseUpdate: api.testUseUpdate<ExtensionT>
  toggleChatDefaultDisableNotification: api.toggleChatDefaultDisableNotification<ExtensionT>
  toggleChatIsMarkedAsUnread: api.toggleChatIsMarkedAsUnread<ExtensionT>
  toggleChatIsPinned: api.toggleChatIsPinned<ExtensionT>
  toggleSupergroupIsAllHistoryAvailable: api.toggleSupergroupIsAllHistoryAvailable<ExtensionT>
  toggleSupergroupSignMessages: api.toggleSupergroupSignMessages<ExtensionT>
  unblockUser: api.unblockUser<ExtensionT>
  unpinChatMessage: api.unpinChatMessage<ExtensionT>
  upgradeBasicGroupChatToSupergroupChat: api.upgradeBasicGroupChatToSupergroupChat<ExtensionT>
  uploadFile: api.uploadFile<ExtensionT>
  uploadStickerFile: api.uploadStickerFile<ExtensionT>
  validateOrderInfo: api.validateOrderInfo<ExtensionT>
  viewMessages: api.viewMessages<ExtensionT>
  viewTrendingStickerSets: api.viewTrendingStickerSets<ExtensionT>
  writeGeneratedFilePart: api.writeGeneratedFilePart<ExtensionT>
}
