/*tslint:disable:ordered-imports*/

import * as account from './methods/account'
import * as auth from './methods/auth'
import * as bots from './methods/bots'
import * as channels from './methods/channels'
import * as contacts from './methods/contacts'
import * as help from './methods/help'
import * as langpack from './methods/langpack'
import * as messages from './methods/messages'
import * as payments from './methods/payments'
import * as phone from './methods/phone'
import * as photos from './methods/photos'
import * as stickers from './methods/stickers'
import * as updates from './methods/updates'
import * as upload from './methods/upload'
import * as users from './methods/users'

export {
  account,
  auth,
  bots,
  channels,
  contacts,
  help,
  langpack,
  messages,
  payments,
  phone,
  photos,
  stickers,
  updates,
  upload,
  users
}

export * from './types/AccountAuthorizations'
export * from './types/AccountDaysTtl'
export * from './types/AccountPassword'
export * from './types/AccountPasswordSettings'
export * from './types/AccountPasswordSettings'
export * from './types/AccountPrivacyRules'
export * from './types/AccountTmpPassword'
export * from './types/AuthAuthorization'
export * from './types/AuthCheckedPhone'
export * from './types/AuthCodeType'
export * from './types/AuthExportedAuthorization'
export * from './types/AuthPasswordRecovery'
export * from './types/AuthSentCode'
export * from './types/AuthSentCodeType'
export * from './types/Authorization'
export * from './types/BotCommand'
export * from './types/BotInfo'
export * from './types/BotInlineMessage'
export * from './types/BotInlineResult'
export * from './types/CdnConfig'
export * from './types/CdnFileHash'
export * from './types/CdnPublicKey'
export * from './types/ChannelAdminLogEvent'
export * from './types/ChannelAdminLogEventAction'
export * from './types/ChannelAdminLogEventsFilter'
export * from './types/ChannelAdminRights'
export * from './types/ChannelBannedRights'
export * from './types/ChannelMessagesFilter'
export * from './types/ChannelParticipant'
export * from './types/ChannelParticipantsFilter'
export * from './types/ChannelsAdminLogResults'
export * from './types/ChannelsChannelParticipant'
export * from './types/ChannelsChannelParticipants'
export * from './types/Chat'
export * from './types/ChatFull'
export * from './types/ChatInvite'
export * from './types/ChatParticipant'
export * from './types/ChatParticipants'
export * from './types/ChatPhoto'
export * from './types/Config'
export * from './types/Contact'
export * from './types/ContactBlocked'
export * from './types/ContactLink'
export * from './types/ContactStatus'
export * from './types/ContactsBlocked'
export * from './types/ContactsContacts'
export * from './types/ContactsFound'
export * from './types/ContactsImportedContacts'
export * from './types/ContactsLink'
export * from './types/ContactsResolvedPeer'
export * from './types/ContactsTopPeers'
export * from './types/DataJson'
export * from './types/DcOption'
export * from './types/Dialog'
export * from './types/DisabledFeature'
export * from './types/Document'
export * from './types/DocumentAttribute'
export * from './types/DraftMessage'
export * from './types/EncryptedChat'
export * from './types/EncryptedFile'
export * from './types/EncryptedMessage'
export * from './types/Error'
export * from './types/ExportedChatInvite'
export * from './types/ExportedMessageLink'
export * from './types/FileLocation'
export * from './types/FoundGif'
export * from './types/Game'
export * from './types/GeoPoint'
export * from './types/HelpAppUpdate'
export * from './types/HelpInviteText'
export * from './types/HelpSupport'
export * from './types/HelpTermsOfService'
export * from './types/HighScore'
export * from './types/ImportedContact'
export * from './types/InlineBotSwitchPm'
export * from './types/InputAppEvent'
export * from './types/InputBotInlineMessage'
export * from './types/InputBotInlineMessageId'
export * from './types/InputBotInlineResult'
export * from './types/InputChannel'
export * from './types/InputChatPhoto'
export * from './types/InputContact'
export * from './types/InputDocument'
export * from './types/InputEncryptedChat'
export * from './types/InputEncryptedFile'
export * from './types/InputFile'
export * from './types/InputFileLocation'
export * from './types/InputGame'
export * from './types/InputGeoPoint'
export * from './types/InputMedia'
export * from './types/InputNotifyPeer'
export * from './types/InputPaymentCredentials'
export * from './types/InputPeer'
export * from './types/InputPeerNotifyEvents'
export * from './types/InputPeerNotifySettings'
export * from './types/InputPhoneCall'
export * from './types/InputPhoto'
export * from './types/InputPrivacyKey'
export * from './types/InputPrivacyRule'
export * from './types/InputStickerSet'
export * from './types/InputStickerSetItem'
export * from './types/InputStickeredMedia'
export * from './types/InputUser'
export * from './types/InputWebDocument'
export * from './types/InputWebFileLocation'
export * from './types/Invoice'
export * from './types/KeyboardButton'
export * from './types/KeyboardButtonRow'
export * from './types/LabeledPrice'
export * from './types/LangPackDifference'
export * from './types/LangPackLanguage'
export * from './types/LangPackString'
export * from './types/MaskCoords'
export * from './types/Message'
export * from './types/MessageAction'
export * from './types/MessageEntity'
export * from './types/MessageFwdHeader'
export * from './types/MessageMedia'
export * from './types/MessageRange'
export * from './types/MessagesAffectedHistory'
export * from './types/MessagesAffectedMessages'
export * from './types/MessagesAllStickers'
export * from './types/MessagesArchivedStickers'
export * from './types/MessagesBotCallbackAnswer'
export * from './types/MessagesBotResults'
export * from './types/MessagesChatFull'
export * from './types/MessagesChats'
export * from './types/MessagesDhConfig'
export * from './types/MessagesDialogs'
export * from './types/MessagesFavedStickers'
export * from './types/MessagesFeaturedStickers'
export * from './types/MessagesFilter'
export * from './types/MessagesFoundGifs'
export * from './types/MessagesHighScores'
export * from './types/MessagesMessageEditData'
export * from './types/MessagesMessages'
export * from './types/MessagesPeerDialogs'
export * from './types/MessagesRecentStickers'
export * from './types/MessagesSavedGifs'
export * from './types/MessagesSentEncryptedMessage'
export * from './types/MessagesStickerSet'
export * from './types/MessagesStickerSetInstallResult'
export * from './types/MessagesStickers'
export * from './types/NearestDc'
export * from './types/NotifyPeer'
export * from './types/Null'
export * from './types/Page'
export * from './types/PageBlock'
export * from './types/PaymentCharge'
export * from './types/PaymentRequestedInfo'
export * from './types/PaymentSavedCredentials'
export * from './types/PaymentsPaymentForm'
export * from './types/PaymentsPaymentReceipt'
export * from './types/PaymentsPaymentResult'
export * from './types/PaymentsSavedInfo'
export * from './types/PaymentsValidatedRequestedInfo'
export * from './types/Peer'
export * from './types/PeerNotifyEvents'
export * from './types/PeerNotifySettings'
export * from './types/PeerSettings'
export * from './types/PhoneCall'
export * from './types/PhoneCallDiscardReason'
export * from './types/PhoneCallProtocol'
export * from './types/PhoneConnection'
export * from './types/PhonePhoneCall'
export * from './types/Photo'
export * from './types/PhotoSize'
export * from './types/PhotosPhoto'
export * from './types/PhotosPhotos'
export * from './types/PopularContact'
export * from './types/PostAddress'
export * from './types/PrivacyKey'
export * from './types/PrivacyRule'
export * from './types/ReceivedNotifyMessage'
export * from './types/ReplyMarkup'
export * from './types/ReportReason'
export * from './types/RichText'
export * from './types/SendMessageAction'
export * from './types/ShippingOption'
export * from './types/StickerPack'
export * from './types/StickerSet'
export * from './types/StickerSetCovered'
export * from './types/StorageFileType'
export * from './types/TopPeer'
export * from './types/TopPeerCategory'
export * from './types/TopPeerCategoryPeers'
export * from './types/True'
export * from './types/Update'
export * from './types/Updates'
export * from './types/UpdatesChannelDifference'
export * from './types/UpdatesDifference'
export * from './types/UpdatesState'
export * from './types/UploadCdnFile'
export * from './types/UploadFile'
export * from './types/UploadWebFile'
export * from './types/User'
export * from './types/UserFull'
export * from './types/UserProfilePhoto'
export * from './types/UserStatus'
export * from './types/WallPaper'
export * from './types/WebDocument'
export * from './types/WebPage'
