/** Points to a file */
export type InputFileUnion = InputFileId
  | InputFileRemote
  | InputFileLocal
  | InputFileGenerated

/** A file defined by its unique ID */
export interface InputFileId {
  _: 'inputFileId'
  /** Unique file identifier */
  id: number
}

/** A file defined by its remote ID */
export interface InputFileRemote {
  _: 'inputFileRemote'
  /** Remote file identifier */
  id: string
}

/** A file defined by a local path */
export interface InputFileLocal {
  _: 'inputFileLocal'
  /** Local path to the file */
  path: string
}

/** A file generated by the client */
export interface InputFileGenerated {
  _: 'inputFileGenerated'
  /**
   * Local path to a file from which the file is generated; may be empty if there is no
   * such file
   */
  originalPath: string
  /**
   * String specifying the conversion applied to the original file; should be persistent
   * across application restarts. Conversions beginning with '#' are reserved for internal
   * TDLib usage
   */
  conversion: string
  /** Expected size of the generated file; 0 if unknown */
  expectedSize: number
}
