/** A file generated by the client */
export class InputFileGeneratedBaseModel {
  public _: 'inputFileGenerated'
  /**
   * Local path to a file from which the file is generated; may be empty if there is no
   * such file
   */
  public originalPath: string
  /**
   * String specifying the conversion applied to the original file; should be persistent
   * across application restarts
   */
  public conversion: string
  /** Expected size of the generated file; 0 if unknown */
  public expectedSize: number
}
